language: java

jdk:
  - openjdk8
  - oraclejdk8
#  - oraclejdk9

env:
  global: 
    - TERM=dumb
  matrix:
  - IDEA_VERSION=2016.3.1
  - IDEA_VERSION=2017.3.1
  - IDEA_VERSION=2017.3.1

#install:
#- ./gradlew --version
#- ./gradlew jar testClasses
#
#script:
#- jdk_switcher use ${TEST_JRE}
#- ./gradlew --version
#- ./gradlew check

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/