language: java

jdk:
#  - oraclejdk8
#  - oraclejdk9
  - openjdk8
env:
  - IJVERSION=2016.3.1
  - TEST_JRE=oraclejdk8 IJVERSION=2017.3.1
  - TEST_JRE=oraclejdk9 IJVERSION=2017.3.1
  - IJVERSION=LATEST_EAP

install:
- ./gradlew --version
- ./gradlew jar testClasses

script:
- jdk_switcher use ${TEST_JRE}
- ./gradlew --version
- ./gradlew check